export enum Evenement {
  SeRetourneDosVentre = "Se retourne du dos sur le ventre",
  SeRetourneVentreDos = "Se retourne du ventre sur le dos",
  SAssiedSeul = "S'assied seul",
  SeMetDeboutAvecSupport = "Se met debout avec un support",
  MarcheSeul = "Marche seul",
  MangeSeul = "Mange seul",
  BoitSeulAuVerre = "Boit seul au verre",
  GouteUnNouvelAliment = "Goûte un nouvel aliment",
  FaitLaSieste = "Fait la sieste",
  SeReveilleDeLaSieste = "Se réveille de la sieste",
  ParticipeAuChange = "Participe au change",
  UtiliseLePot = "Utilise le pot",
  DitUnNouveauMot = "Dit un nouveau mot",
  ExprimeUnBesoin = "Exprime un besoin",
  RepondASonPrenom = "Répond à son prénom",
  ParticipeAUneActivite = "Participe à une activité",
  JoueAvecLesAutresEnfants = "Joue avec les autres enfants",
  ParticipeAUnJeuCollectif = "Participe à un jeu collectif",
  ExprimeUneEmotion = "Exprime une émotion",
  RealiseUneNouvelleAcquisition = "Réalise une nouvelle acquisition",
  PartageUnJouet = "Partage un jouet",
  ExploreUnLivre = "Explore un livre",
  JoueEnExterieur = "Joue en extérieur",
  SEndortSeul = "S'endort seul",
  SeLaveLesMainsAvecAide = "Se lave les mains avec aide",
  Autre = "Autre",
}
