// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'fc0b0f1853a7246003079ebba194195c6faf9b32856acea494b1f79daeec382f'>;
export type ExecutionHash =
  ExecutionHashBase<'bd5220a3ef0a68da045ec490ab727d1d03b5c51a64b07b77bc5859e6627ceef7'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Dejection: {
      readonly id: Char<36>;
      readonly type: CodecTypes['pg/text@1']['output'] | null;
      readonly date: CodecTypes['pg/date-string@1']['output'] | null;
      readonly commentaire: CodecTypes['pg/text@1']['output'] | null;
      readonly auteurId: Char<36> | null;
      readonly transmissionSoirId: Char<36>;
    };
    readonly Enfant: {
      readonly id: Char<36>;
      readonly dateArrive: CodecTypes['pg/date-string@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-string@1']['output'];
    };
    readonly HistoireEnfant: {
      readonly id: Char<36>;
      readonly annee: CodecTypes['pg/int4@1']['output'] | null;
      readonly histoire: CodecTypes['pg/text@1']['output'] | null;
      readonly dateCreation: CodecTypes['pg/timestamp-string@1']['output'];
      readonly dateModification: CodecTypes['pg/timestamp-string@1']['output'] | null;
      readonly auteurId: Char<36> | null;
      readonly enfantId: Char<36>;
    };
    readonly Journal: {
      readonly id: Char<36>;
      readonly nom: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-string@1']['output'];
      readonly enfantId: Char<36>;
    };
    readonly Personnel: {
      readonly id: Char<36>;
      readonly role: CodecTypes['pg/text@1']['output'];
      readonly prenom: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamp-string@1']['output'];
    };
    readonly Presence: {
      readonly id: Char<36>;
      readonly etatPresence: CodecTypes['pg/text@1']['output'] | null;
      readonly datePresence: CodecTypes['pg/date-string@1']['output'];
      readonly heureArrivee: CodecTypes['pg/time-string@1']['output'] | null;
      readonly auteurId: Char<36> | null;
      readonly enfantId: Char<36>;
    };
    readonly ProblemeSante: {
      readonly id: Char<36>;
      readonly symptome: CodecTypes['pg/text@1']['output'] | null;
      readonly traitement: CodecTypes['pg/text@1']['output'] | null;
      readonly observation: CodecTypes['pg/text@1']['output'] | null;
      readonly transmissionMatinId: Char<36> | null;
      readonly transmissionSoirId: Char<36> | null;
      readonly auteurId: Char<36> | null;
    };
    readonly RappelParent: {
      readonly id: Char<36>;
      readonly message: CodecTypes['pg/text@1']['output'] | null;
      readonly dateCreation: CodecTypes['pg/timestamp-string@1']['output'];
      readonly journeeId: Char<36> | null;
      readonly auteurId: Char<36> | null;
    };
    readonly Temperature: {
      readonly id: Char<36>;
      readonly heure: CodecTypes['pg/time-string@1']['output'] | null;
      readonly temperature: CodecTypes['pg/numeric@1']['output'] | null;
      readonly auteurId: Char<36> | null;
      readonly transmissionSoirId: Char<36> | null;
      readonly problemeSanteId: Char<36> | null;
    };
    readonly TransmissionMatin: {
      readonly id: Char<36>;
      readonly heureCouche: CodecTypes['pg/time-string@1']['output'] | null;
      readonly heureReveille: CodecTypes['pg/time-string@1']['output'] | null;
      readonly observation: CodecTypes['pg/text@1']['output'] | null;
      readonly repas: CodecTypes['pg/text@1']['output'] | null;
      readonly comportement: CodecTypes['pg/text@1']['output'] | null;
      readonly journalId: Char<36>;
      readonly auteurId: Char<36> | null;
    };
    readonly TransmissionSoir: {
      readonly id: Char<36>;
      readonly depart: CodecTypes['pg/time-string@1']['output'] | null;
      readonly arrivee: CodecTypes['pg/time-string@1']['output'] | null;
      readonly observation: CodecTypes['pg/text@1']['output'] | null;
      readonly evenement: CodecTypes['pg/text@1']['output'] | null;
      readonly besoin: CodecTypes['pg/text@1']['output'] | null;
      readonly journalId: Char<36>;
      readonly auteurId: Char<36> | null;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Dejection: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly type: CodecTypes['pg/text@1']['input'] | null;
      readonly date: CodecTypes['pg/date-string@1']['input'] | null;
      readonly commentaire: CodecTypes['pg/text@1']['input'] | null;
      readonly auteurId: CodecTypes['sql/char@1']['input'] | null;
      readonly transmissionSoirId: CodecTypes['sql/char@1']['input'];
    };
    readonly Enfant: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly dateArrive: CodecTypes['pg/date-string@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamp-string@1']['input'];
    };
    readonly HistoireEnfant: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly annee: CodecTypes['pg/int4@1']['input'] | null;
      readonly histoire: CodecTypes['pg/text@1']['input'] | null;
      readonly dateCreation: CodecTypes['pg/timestamp-string@1']['input'];
      readonly dateModification: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly auteurId: CodecTypes['sql/char@1']['input'] | null;
      readonly enfantId: CodecTypes['sql/char@1']['input'];
    };
    readonly Journal: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly nom: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-string@1']['input'];
      readonly enfantId: CodecTypes['sql/char@1']['input'];
    };
    readonly Personnel: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly role: CodecTypes['pg/text@1']['input'];
      readonly prenom: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamp-string@1']['input'];
    };
    readonly Presence: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly etatPresence: CodecTypes['pg/text@1']['input'] | null;
      readonly datePresence: CodecTypes['pg/date-string@1']['input'];
      readonly heureArrivee: CodecTypes['pg/time-string@1']['input'] | null;
      readonly auteurId: CodecTypes['sql/char@1']['input'] | null;
      readonly enfantId: CodecTypes['sql/char@1']['input'];
    };
    readonly ProblemeSante: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly symptome: CodecTypes['pg/text@1']['input'] | null;
      readonly traitement: CodecTypes['pg/text@1']['input'] | null;
      readonly observation: CodecTypes['pg/text@1']['input'] | null;
      readonly transmissionMatinId: CodecTypes['sql/char@1']['input'] | null;
      readonly transmissionSoirId: CodecTypes['sql/char@1']['input'] | null;
      readonly auteurId: CodecTypes['sql/char@1']['input'] | null;
    };
    readonly RappelParent: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly message: CodecTypes['pg/text@1']['input'] | null;
      readonly dateCreation: CodecTypes['pg/timestamp-string@1']['input'];
      readonly journeeId: CodecTypes['sql/char@1']['input'] | null;
      readonly auteurId: CodecTypes['sql/char@1']['input'] | null;
    };
    readonly Temperature: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly heure: CodecTypes['pg/time-string@1']['input'] | null;
      readonly temperature: CodecTypes['pg/numeric@1']['input'] | null;
      readonly auteurId: CodecTypes['sql/char@1']['input'] | null;
      readonly transmissionSoirId: CodecTypes['sql/char@1']['input'] | null;
      readonly problemeSanteId: CodecTypes['sql/char@1']['input'] | null;
    };
    readonly TransmissionMatin: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly heureCouche: CodecTypes['pg/time-string@1']['input'] | null;
      readonly heureReveille: CodecTypes['pg/time-string@1']['input'] | null;
      readonly observation: CodecTypes['pg/text@1']['input'] | null;
      readonly repas: CodecTypes['pg/text@1']['input'] | null;
      readonly comportement: CodecTypes['pg/text@1']['input'] | null;
      readonly journalId: CodecTypes['sql/char@1']['input'];
      readonly auteurId: CodecTypes['sql/char@1']['input'] | null;
    };
    readonly TransmissionSoir: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly depart: CodecTypes['pg/time-string@1']['input'] | null;
      readonly arrivee: CodecTypes['pg/time-string@1']['input'] | null;
      readonly observation: CodecTypes['pg/text@1']['input'] | null;
      readonly evenement: CodecTypes['pg/text@1']['input'] | null;
      readonly besoin: CodecTypes['pg/text@1']['input'] | null;
      readonly journalId: CodecTypes['sql/char@1']['input'];
      readonly auteurId: CodecTypes['sql/char@1']['input'] | null;
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly dejection: {
      readonly auteur_id: Char<36> | null;
      readonly commentaire: CodecTypes['pg/text@1']['output'] | null;
      readonly date: CodecTypes['pg/date-string@1']['output'] | null;
      readonly id: Char<36>;
      readonly transmission_soir_id: Char<36>;
      readonly type: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly enfant: {
      readonly created_at: CodecTypes['pg/timestamp-string@1']['output'];
      readonly date_arrive: CodecTypes['pg/date-string@1']['output'] | null;
      readonly id: Char<36>;
    };
    readonly histoire_enfant: {
      readonly annee: CodecTypes['pg/int4@1']['output'] | null;
      readonly auteur_id: Char<36> | null;
      readonly date_creation: CodecTypes['pg/timestamp-string@1']['output'];
      readonly date_modification: CodecTypes['pg/timestamp-string@1']['output'] | null;
      readonly enfant_id: Char<36>;
      readonly histoire: CodecTypes['pg/text@1']['output'] | null;
      readonly id: Char<36>;
    };
    readonly journal: {
      readonly created_at: CodecTypes['pg/timestamp-string@1']['output'];
      readonly enfant_id: Char<36>;
      readonly id: Char<36>;
      readonly nom: CodecTypes['pg/text@1']['output'];
    };
    readonly personnel: {
      readonly created_at: CodecTypes['pg/timestamp-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: Char<36>;
      readonly password: CodecTypes['pg/text@1']['output'];
      readonly prenom: CodecTypes['pg/text@1']['output'];
      readonly role: CodecTypes['pg/text@1']['output'];
    };
    readonly presence: {
      readonly auteur_id: Char<36> | null;
      readonly date_presence: CodecTypes['pg/date-string@1']['output'];
      readonly enfant_id: Char<36>;
      readonly etat_presence: CodecTypes['pg/text@1']['output'] | null;
      readonly heure_arrivee: CodecTypes['pg/time-string@1']['output'] | null;
      readonly id: Char<36>;
    };
    readonly probleme_sante: {
      readonly auteur_id: Char<36> | null;
      readonly id: Char<36>;
      readonly observation: CodecTypes['pg/text@1']['output'] | null;
      readonly symptome: CodecTypes['pg/text@1']['output'] | null;
      readonly traitement: CodecTypes['pg/text@1']['output'] | null;
      readonly transmission_matin_id: Char<36> | null;
      readonly transmission_soir_id: Char<36> | null;
    };
    readonly rappel_parent: {
      readonly auteur_id: Char<36> | null;
      readonly date_creation: CodecTypes['pg/timestamp-string@1']['output'];
      readonly id: Char<36>;
      readonly journee_id: Char<36> | null;
      readonly message: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly temperature: {
      readonly auteur_id: Char<36> | null;
      readonly heure: CodecTypes['pg/time-string@1']['output'] | null;
      readonly id: Char<36>;
      readonly probleme_sante_id: Char<36> | null;
      readonly temperature: CodecTypes['pg/numeric@1']['output'] | null;
      readonly transmission_soir_id: Char<36> | null;
    };
    readonly transmission_matin: {
      readonly auteur_id: Char<36> | null;
      readonly comportement: CodecTypes['pg/text@1']['output'] | null;
      readonly heure_couche: CodecTypes['pg/time-string@1']['output'] | null;
      readonly heure_reveille: CodecTypes['pg/time-string@1']['output'] | null;
      readonly id: Char<36>;
      readonly journal_id: Char<36>;
      readonly observation: CodecTypes['pg/text@1']['output'] | null;
      readonly repas: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly transmission_soir: {
      readonly arrivee: CodecTypes['pg/time-string@1']['output'] | null;
      readonly auteur_id: Char<36> | null;
      readonly besoin: CodecTypes['pg/text@1']['output'] | null;
      readonly depart: CodecTypes['pg/time-string@1']['output'] | null;
      readonly evenement: CodecTypes['pg/text@1']['output'] | null;
      readonly id: Char<36>;
      readonly journal_id: Char<36>;
      readonly observation: CodecTypes['pg/text@1']['output'] | null;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly dejection: {
      readonly auteur_id: CodecTypes['sql/char@1']['input'] | null;
      readonly commentaire: CodecTypes['pg/text@1']['input'] | null;
      readonly date: CodecTypes['pg/date-string@1']['input'] | null;
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly transmission_soir_id: CodecTypes['sql/char@1']['input'];
      readonly type: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly enfant: {
      readonly created_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly date_arrive: CodecTypes['pg/date-string@1']['input'] | null;
      readonly id: CodecTypes['sql/char@1']['input'];
    };
    readonly histoire_enfant: {
      readonly annee: CodecTypes['pg/int4@1']['input'] | null;
      readonly auteur_id: CodecTypes['sql/char@1']['input'] | null;
      readonly date_creation: CodecTypes['pg/timestamp-string@1']['input'];
      readonly date_modification: CodecTypes['pg/timestamp-string@1']['input'] | null;
      readonly enfant_id: CodecTypes['sql/char@1']['input'];
      readonly histoire: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['sql/char@1']['input'];
    };
    readonly journal: {
      readonly created_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly enfant_id: CodecTypes['sql/char@1']['input'];
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly nom: CodecTypes['pg/text@1']['input'];
    };
    readonly personnel: {
      readonly created_at: CodecTypes['pg/timestamp-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly password: CodecTypes['pg/text@1']['input'];
      readonly prenom: CodecTypes['pg/text@1']['input'];
      readonly role: CodecTypes['pg/text@1']['input'];
    };
    readonly presence: {
      readonly auteur_id: CodecTypes['sql/char@1']['input'] | null;
      readonly date_presence: CodecTypes['pg/date-string@1']['input'];
      readonly enfant_id: CodecTypes['sql/char@1']['input'];
      readonly etat_presence: CodecTypes['pg/text@1']['input'] | null;
      readonly heure_arrivee: CodecTypes['pg/time-string@1']['input'] | null;
      readonly id: CodecTypes['sql/char@1']['input'];
    };
    readonly probleme_sante: {
      readonly auteur_id: CodecTypes['sql/char@1']['input'] | null;
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly observation: CodecTypes['pg/text@1']['input'] | null;
      readonly symptome: CodecTypes['pg/text@1']['input'] | null;
      readonly traitement: CodecTypes['pg/text@1']['input'] | null;
      readonly transmission_matin_id: CodecTypes['sql/char@1']['input'] | null;
      readonly transmission_soir_id: CodecTypes['sql/char@1']['input'] | null;
    };
    readonly rappel_parent: {
      readonly auteur_id: CodecTypes['sql/char@1']['input'] | null;
      readonly date_creation: CodecTypes['pg/timestamp-string@1']['input'];
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly journee_id: CodecTypes['sql/char@1']['input'] | null;
      readonly message: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly temperature: {
      readonly auteur_id: CodecTypes['sql/char@1']['input'] | null;
      readonly heure: CodecTypes['pg/time-string@1']['input'] | null;
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly probleme_sante_id: CodecTypes['sql/char@1']['input'] | null;
      readonly temperature: CodecTypes['pg/numeric@1']['input'] | null;
      readonly transmission_soir_id: CodecTypes['sql/char@1']['input'] | null;
    };
    readonly transmission_matin: {
      readonly auteur_id: CodecTypes['sql/char@1']['input'] | null;
      readonly comportement: CodecTypes['pg/text@1']['input'] | null;
      readonly heure_couche: CodecTypes['pg/time-string@1']['input'] | null;
      readonly heure_reveille: CodecTypes['pg/time-string@1']['input'] | null;
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly journal_id: CodecTypes['sql/char@1']['input'];
      readonly observation: CodecTypes['pg/text@1']['input'] | null;
      readonly repas: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly transmission_soir: {
      readonly arrivee: CodecTypes['pg/time-string@1']['input'] | null;
      readonly auteur_id: CodecTypes['sql/char@1']['input'] | null;
      readonly besoin: CodecTypes['pg/text@1']['input'] | null;
      readonly depart: CodecTypes['pg/time-string@1']['input'] | null;
      readonly evenement: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly journal_id: CodecTypes['sql/char@1']['input'];
      readonly observation: CodecTypes['pg/text@1']['input'] | null;
    };
  };
};

export namespace Models {
  export type public_Personnel = {
    id: Char<36>;
    role: CodecTypes['pg/text@1']['output'];
    prenom: CodecTypes['pg/text@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    password: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamp-string@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_Enfant = {
    id: Char<36>;
    dateArrive: CodecTypes['pg/date-string@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamp-string@1']['output'];
    readonly [RelationKeys]?: never;
  };
  export type public_HistoireEnfant = {
    id: Char<36>;
    annee: CodecTypes['pg/int4@1']['output'] | null;
    histoire: CodecTypes['pg/text@1']['output'] | null;
    dateCreation: CodecTypes['pg/timestamp-string@1']['output'];
    dateModification: CodecTypes['pg/timestamp-string@1']['output'] | null;
    auteurId: Char<36> | null;
    enfantId: Char<36>;
    readonly [RelationKeys]?: never;
  };
  export type public_Presence = {
    id: Char<36>;
    etatPresence: CodecTypes['pg/text@1']['output'] | null;
    datePresence: CodecTypes['pg/date-string@1']['output'];
    heureArrivee: CodecTypes['pg/time-string@1']['output'] | null;
    auteurId: Char<36> | null;
    enfantId: Char<36>;
    readonly [RelationKeys]?: never;
  };
  export type public_Journal = {
    id: Char<36>;
    nom: CodecTypes['pg/text@1']['output'];
    createdAt: CodecTypes['pg/timestamp-string@1']['output'];
    enfantId: Char<36>;
    readonly [RelationKeys]?: never;
  };
  export type public_TransmissionMatin = {
    id: Char<36>;
    heureCouche: CodecTypes['pg/time-string@1']['output'] | null;
    heureReveille: CodecTypes['pg/time-string@1']['output'] | null;
    observation: CodecTypes['pg/text@1']['output'] | null;
    repas: CodecTypes['pg/text@1']['output'] | null;
    comportement: CodecTypes['pg/text@1']['output'] | null;
    journalId: Char<36>;
    auteurId: Char<36> | null;
    readonly [RelationKeys]?: never;
  };
  export type public_TransmissionSoir = {
    id: Char<36>;
    depart: CodecTypes['pg/time-string@1']['output'] | null;
    arrivee: CodecTypes['pg/time-string@1']['output'] | null;
    observation: CodecTypes['pg/text@1']['output'] | null;
    evenement: CodecTypes['pg/text@1']['output'] | null;
    besoin: CodecTypes['pg/text@1']['output'] | null;
    journalId: Char<36>;
    auteurId: Char<36> | null;
    readonly [RelationKeys]?: never;
  };
  export type public_Dejection = {
    id: Char<36>;
    type: CodecTypes['pg/text@1']['output'] | null;
    date: CodecTypes['pg/date-string@1']['output'] | null;
    commentaire: CodecTypes['pg/text@1']['output'] | null;
    auteurId: Char<36> | null;
    transmissionSoirId: Char<36>;
    readonly [RelationKeys]?: never;
  };
  export type public_RappelParent = {
    id: Char<36>;
    message: CodecTypes['pg/text@1']['output'] | null;
    dateCreation: CodecTypes['pg/timestamp-string@1']['output'];
    journeeId: Char<36> | null;
    auteurId: Char<36> | null;
    readonly [RelationKeys]?: never;
  };
  export type public_ProblemeSante = {
    id: Char<36>;
    symptome: CodecTypes['pg/text@1']['output'] | null;
    traitement: CodecTypes['pg/text@1']['output'] | null;
    observation: CodecTypes['pg/text@1']['output'] | null;
    transmissionMatinId: Char<36> | null;
    transmissionSoirId: Char<36> | null;
    auteurId: Char<36> | null;
    readonly [RelationKeys]?: never;
  };
  export type public_Temperature = {
    id: Char<36>;
    heure: CodecTypes['pg/time-string@1']['output'] | null;
    temperature: CodecTypes['pg/numeric@1']['output'] | null;
    auteurId: Char<36> | null;
    transmissionSoirId: Char<36> | null;
    problemeSanteId: Char<36> | null;
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  public: {
    Personnel: Models.public_Personnel;
    Enfant: Models.public_Enfant;
    HistoireEnfant: Models.public_HistoireEnfant;
    Presence: Models.public_Presence;
    Journal: Models.public_Journal;
    TransmissionMatin: Models.public_TransmissionMatin;
    TransmissionSoir: Models.public_TransmissionSoir;
    Dejection: Models.public_Dejection;
    RappelParent: Models.public_RappelParent;
    ProblemeSante: Models.public_ProblemeSante;
    Temperature: Models.public_Temperature;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly dejection: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly date: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: true;
                };
                readonly commentaire: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly auteur_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly transmission_soir_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly enfant: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly date_arrive: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly histoire_enfant: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly annee: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly histoire: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly date_creation: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                };
                readonly date_modification: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: true;
                };
                readonly auteur_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly enfant_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly journal: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly nom: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                };
                readonly enfant_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly personnel: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly role: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly prenom: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly password: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly presence: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly etat_presence: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly date_presence: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly heure_arrivee: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-string@1';
                  readonly nullable: true;
                };
                readonly auteur_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly enfant_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly probleme_sante: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly symptome: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly traitement: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly observation: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly transmission_matin_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly transmission_soir_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly auteur_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly rappel_parent: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly message: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly date_creation: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-string@1';
                  readonly nullable: false;
                };
                readonly journee_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly auteur_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly temperature: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly heure: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-string@1';
                  readonly nullable: true;
                };
                readonly temperature: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly auteur_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly transmission_soir_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly probleme_sante_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly transmission_matin: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly heure_couche: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-string@1';
                  readonly nullable: true;
                };
                readonly heure_reveille: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-string@1';
                  readonly nullable: true;
                };
                readonly observation: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly repas: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly comportement: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly journal_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly auteur_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly transmission_soir: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly depart: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-string@1';
                  readonly nullable: true;
                };
                readonly arrivee: {
                  readonly nativeType: 'time';
                  readonly codecId: 'pg/time-string@1';
                  readonly nullable: true;
                };
                readonly observation: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly evenement: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly besoin: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly journal_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly auteur_id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly personnel: { readonly namespace: 'public' & NamespaceId; readonly model: 'Personnel' };
    readonly enfant: { readonly namespace: 'public' & NamespaceId; readonly model: 'Enfant' };
    readonly histoire_enfant: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'HistoireEnfant';
    };
    readonly presence: { readonly namespace: 'public' & NamespaceId; readonly model: 'Presence' };
    readonly journal: { readonly namespace: 'public' & NamespaceId; readonly model: 'Journal' };
    readonly transmission_matin: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'TransmissionMatin';
    };
    readonly transmission_soir: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'TransmissionSoir';
    };
    readonly dejection: { readonly namespace: 'public' & NamespaceId; readonly model: 'Dejection' };
    readonly rappel_parent: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'RappelParent';
    };
    readonly probleme_sante: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ProblemeSante';
    };
    readonly temperature: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Temperature';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Dejection: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly type: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly date: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly commentaire: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly auteurId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly transmissionSoirId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'dejection';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly type: { readonly column: 'type' };
                readonly date: { readonly column: 'date' };
                readonly commentaire: { readonly column: 'commentaire' };
                readonly auteurId: { readonly column: 'auteur_id' };
                readonly transmissionSoirId: { readonly column: 'transmission_soir_id' };
              };
            };
          };
          readonly Enfant: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly dateArrive: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'enfant';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly dateArrive: { readonly column: 'date_arrive' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly HistoireEnfant: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly annee: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly histoire: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly dateCreation: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                };
              };
              readonly dateModification: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                };
              };
              readonly auteurId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly enfantId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'histoire_enfant';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly annee: { readonly column: 'annee' };
                readonly histoire: { readonly column: 'histoire' };
                readonly dateCreation: { readonly column: 'date_creation' };
                readonly dateModification: { readonly column: 'date_modification' };
                readonly auteurId: { readonly column: 'auteur_id' };
                readonly enfantId: { readonly column: 'enfant_id' };
              };
            };
          };
          readonly Journal: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly nom: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                };
              };
              readonly enfantId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'journal';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nom: { readonly column: 'nom' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly enfantId: { readonly column: 'enfant_id' };
              };
            };
          };
          readonly Personnel: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly prenom: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'personnel';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly role: { readonly column: 'role' };
                readonly prenom: { readonly column: 'prenom' };
                readonly email: { readonly column: 'email' };
                readonly password: { readonly column: 'password' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly Presence: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly etatPresence: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly datePresence: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly heureArrivee: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-string@1' };
              };
              readonly auteurId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly enfantId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'presence';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly etatPresence: { readonly column: 'etat_presence' };
                readonly datePresence: { readonly column: 'date_presence' };
                readonly heureArrivee: { readonly column: 'heure_arrivee' };
                readonly auteurId: { readonly column: 'auteur_id' };
                readonly enfantId: { readonly column: 'enfant_id' };
              };
            };
          };
          readonly ProblemeSante: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly symptome: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly traitement: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly observation: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly transmissionMatinId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly transmissionSoirId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly auteurId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'probleme_sante';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly symptome: { readonly column: 'symptome' };
                readonly traitement: { readonly column: 'traitement' };
                readonly observation: { readonly column: 'observation' };
                readonly transmissionMatinId: { readonly column: 'transmission_matin_id' };
                readonly transmissionSoirId: { readonly column: 'transmission_soir_id' };
                readonly auteurId: { readonly column: 'auteur_id' };
              };
            };
          };
          readonly RappelParent: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly message: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly dateCreation: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-string@1';
                };
              };
              readonly journeeId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly auteurId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'rappel_parent';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly message: { readonly column: 'message' };
                readonly dateCreation: { readonly column: 'date_creation' };
                readonly journeeId: { readonly column: 'journee_id' };
                readonly auteurId: { readonly column: 'auteur_id' };
              };
            };
          };
          readonly Temperature: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly heure: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-string@1' };
              };
              readonly temperature: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly auteurId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly transmissionSoirId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly problemeSanteId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'temperature';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly heure: { readonly column: 'heure' };
                readonly temperature: { readonly column: 'temperature' };
                readonly auteurId: { readonly column: 'auteur_id' };
                readonly transmissionSoirId: { readonly column: 'transmission_soir_id' };
                readonly problemeSanteId: { readonly column: 'probleme_sante_id' };
              };
            };
          };
          readonly TransmissionMatin: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly heureCouche: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-string@1' };
              };
              readonly heureReveille: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-string@1' };
              };
              readonly observation: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly repas: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly comportement: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly journalId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly auteurId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'transmission_matin';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly heureCouche: { readonly column: 'heure_couche' };
                readonly heureReveille: { readonly column: 'heure_reveille' };
                readonly observation: { readonly column: 'observation' };
                readonly repas: { readonly column: 'repas' };
                readonly comportement: { readonly column: 'comportement' };
                readonly journalId: { readonly column: 'journal_id' };
                readonly auteurId: { readonly column: 'auteur_id' };
              };
            };
          };
          readonly TransmissionSoir: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly depart: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-string@1' };
              };
              readonly arrivee: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/time-string@1' };
              };
              readonly observation: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly evenement: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly besoin: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly journalId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly auteurId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'transmission_soir';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly depart: { readonly column: 'depart' };
                readonly arrivee: { readonly column: 'arrivee' };
                readonly observation: { readonly column: 'observation' };
                readonly evenement: { readonly column: 'evenement' };
                readonly besoin: { readonly column: 'besoin' };
                readonly journalId: { readonly column: 'journal_id' };
                readonly auteurId: { readonly column: 'auteur_id' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'dejection';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'enfant';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'histoire_enfant';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'journal';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'personnel';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'presence';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'probleme_sante';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'rappel_parent';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'temperature';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'transmission_matin';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'transmission_soir';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
