services:
  backend:
    build: ./back
    ports:
      - "3000:3000"
    env_file:
      - ./back/.env
    environment:
      FRONTEND_URL: http://192.168.1.23:4200
    restart: always

  frontend:
    build: ./front
    ports:
      - "4200:4200"
    environment:
      API_URL: http://192.168.1.23:3000
    depends_on:
      - backend
    restart: always